image: node:lts

before_script:
  - npm ci

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - npm run lint
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG !~ /^v.*$/

build:
  stage: test
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_TAG !~ /^v.*$/
  artifacts:
    paths:
      - public
    expire_in: '12 hours'

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*$/
